src/Entity/User.php
<?php

namespace App\Entity;

use Doctrine\ORM\Mapping as ORM;
use Doctrine\Common\Collections\ArrayCollection;
use Symfony\Component\Security\Core\User\UserInterface;
use Symfony\Component\Validator\Constraints as Assert;

use App\Entity\Locale;

/**
* @ORM\Table(name="users")
* @ORM\Entity(repositoryClass="App\Repository\UserRepository")
*/
class User implements UserInterface
{

    /**
    * @ORM\Column(type="integer")
    * @ORM\Id
    * @ORM\GeneratedValue(strategy="AUTO")
    */
    private $id;

    /**
    * @ORM\Column(type="string", length=255, nullable=true)
    * @Assert\NotBlank()
    */
    private $firstname;

    /**
    * @ORM\Column(type="string", length=255, nullable=true)
    */
    private $lastname;

    /**
    * @ORM\Column(type="string", length=1, nullable=true)
    */
    private $gender;

    /**
    * @ORM\Column(type="string", length=100, unique=true)
    */
    private $email;

    /**
    * @ORM\Column(type="string", length=64)
    * @Assert\NotBlank()
    */
    private $password;

    /**
    * @ORM\Column(type="string", length=60, nullable=true)
    */
    private $phone;

    /**
    * @ORM\Column(type="string", length=60, nullable=true)
    */
    private $mobile;

    /**
    * @ORM\ManyToOne(targetEntity="App\Entity\Locale")
    */
    protected $locale;

    /**
    * @ORM\Column(type="text", nullable=true)
    */
    protected $settings;

    /**
    * @ORM\Column(type="string", length=255, nullable=true)
    */
    private $picture;

    /**
    * @ORM\OneToOne(targetEntity="App\Entity\UserInformation", cascade={"persist", "remove"})
    */
    private $information;

    /**
    * @ORM\OneToOne(targetEntity="App\Entity\UserNote", cascade={"persist", "remove"})
    */
    private $note;

    /**
    * @ORM\ManyToMany(targetEntity="App\Entity\Permission")
    */
    protected $permissions;

    /**
    * @ORM\ManyToMany(targetEntity="App\Entity\Role")
    */
    protected $roles = [];

    /**
    * @ORM\Column(type="boolean")
    */
    private $emailConfirmed = false;

    /**
    * @ORM\Column(type="boolean")
    */
    private $phoneConfirmed = false;

    /**
    * @ORM\Column(type="string", length=60, unique=true, nullable=true)
    */
    private $confirmKey;

    /**
    * @ORM\Column(type="datetime")
    */
    protected $creationDate;

    /**
    * @ORM\Column(name="active", type="boolean")
    */
    private $active;

    public function __construct()
    {
        $this->active = true;
        $this->permissions = new ArrayCollection();
        $this->roles = new ArrayCollection();
        // may not be needed, see section on salt below
        // $this->salt = md5(uniqid('', true));
    }

    /**
    * Get the value of Id
    *
    * @return mixed
    */
    public function getId()
    {
        return $this->id;
    }

    /**
    * Set the value of Id
    *
    * @param mixed id
    *
    * @return self
    */
    public function setId($id)
    {
        $this->id = $id;

        return $this;
    }

    /**
    * Get the value of Email
    *
    * @return mixed
    */
    public function getEmail()
    {
        return $this->email;
    }

    /**
    * Set the value of Email
    *
    * @param mixed email
    *
    * @return self
    */
    public function setEmail($email)
    {
        $this->email = $email;

        return $this;
    }

    /**
    * Get the value of Firstname
    *
    * @return mixed
    */
    public function getFirstname()
    {
        return $this->firstname;
    }

    /**
    * Set the value of Firstname
    *
    * @param mixed firstname
    *
    * @return self
    */
    public function setFirstname($firstname)
    {
        $this->firstname = $firstname;

        return $this;
    }

    /**
    * Get the value of Lastname
    *
    * @return mixed
    */
    public function getLastname()
    {
        return $this->lastname;
    }

    /**
    * Set the value of Lastname
    *
    * @param mixed lastname
    *
    * @return self
    */
    public function setLastname($lastname)
    {
        $this->lastname = $lastname;

        return $this;
    }

    /**
     * Get the value of Gender
     *
     * @return mixed
     */
    public function getGender()
    {
        return $this->gender;
    }

    /**
     * Set the value of Gender
     *
     * @param mixed gender
     *
     * @return self
     */
    public function setGender($gender)
    {
        $this->gender = $gender;

        return $this;
    }

    /**
    * Get the value of Lastname
    *
    * @return mixed
    */
    public function getFullname()
    {
        return $this->firstname . ' ' . $this->lastname;
    }

    /**
    * Get the value of Phone
    *
    * @return mixed
    */
    public function getPhone()
    {
        return $this->phone;
    }

    /**
    * Set the value of Phone
    *
    * @param mixed phone
    *
    * @return self
    */
    public function setPhone($phone)
    {
        $this->phone = $phone;

        return $this;
    }

    /**
    * Set the value of Mobile
    *
    * @param mixed mobile
    *
    * @return self
    */
    public function setMobile($mobile)
    {
        $this->mobile = $mobile;

        return $this;
    }

    /**
    * Set the value of Roles
    *
    * @param mixed roles
    *
    * @return self
    */
    public function setRoles($roles)
    {
        $this->roles = $roles;

        return $this;
    }

    /**
    * Get the value of Locale
    *
    * @return mixed
    */
    public function getLocale()
    {
        return $this->locale;
    }

    /**
    * Set the value of Locale
    *
    * @param mixed locale
    *
    * @return self
    */
    public function setLocale($locale)
    {
        $this->locale = $locale;

        return $this;
    }

    /**
    * Get the value of Email Confirmed
    *
    * @return mixed
    */
    public function getEmailConfirmed()
    {
        return $this->emailConfirmed;
    }

    /**
    * Set the value of Email Confirmed
    *
    * @param mixed emailConfirmed
    *
    * @return self
    */
    public function setEmailConfirmed($emailConfirmed)
    {
        $this->emailConfirmed = $emailConfirmed;

        return $this;
    }

    /**
    * Get the value of Phone Confirmed
    *
    * @return mixed
    */
    public function getPhoneConfirmed()
    {
        return $this->phoneConfirmed;
    }

    /**
    * Set the value of Phone Confirmed
    *
    * @param mixed phoneConfirmed
    *
    * @return self
    */
    public function setPhoneConfirmed($phoneConfirmed)
    {
        $this->phoneConfirmed = $phoneConfirmed;

        return $this;
    }

    /**
    * Get the value of Confirm Key
    *
    * @return mixed
    */
    public function getConfirmKey()
    {
        return $this->confirmKey;
    }

    /**
    * Set the value of Confirm Key
    *
    * @param mixed confirmKey
    *
    * @return self
    */
    public function setConfirmKey($confirmKey)
    {
        $this->confirmKey = $confirmKey;

        return $this;
    }

    /**
    * Get the value of Creation Date
    *
    * @return mixed
    */
    public function getCreationDate()
    {
        return $this->creationDate;
    }

    /**
    * Set the value of Creation Date
    *
    * @param mixed creationDate
    *
    * @return self
    */
    public function setCreationDate($creationDate)
    {
        $this->creationDate = $creationDate;

        return $this;
    }

    /**
    * Get the value of Active
    *
    * @return mixed
    */
    public function getActive()
    {
        return $this->active;
    }

    /**
    * Set the value of Active
    *
    * @param mixed active
    *
    * @return self
    */
    public function setActive($active)
    {
        $this->active = $active;

        return $this;
    }

    public function getUsername()
    {
        return $this->email;
    }

    public function getSalt()
    {
        // you *may* need a real salt depending on your encoder
        // see section on salt below
        return null;
    }


    /**
    * Get the value of Password
    *
    * @return mixed
    */
    public function getPassword()
    {
        return $this->password;
    }

    /**
    * Set the value of Password
    *
    * @param mixed password
    *
    * @return self
    */
    public function setPassword($password)
    {
        $this->password = $password;

        return $this;
    }

    public function eraseCredentials()
    {
    }


    public function isAccountNonExpired()
    {
        return true;
    }

    public function isAccountNonLocked()
    {
        return true;
    }

    public function isCredentialsNonExpired()
    {
        return true;
    }

    public function isEnabled()
    {
        return $this->active;
    }

    /** @see \Serializable::serialize() */
    public function serialize()
    {
        return serialize(array(
            $this->id,
            $this->email,
            $this->password,
            $this->active,
            // see section on salt below
            // $this->salt,
        ));
    }

    /** @see \Serializable::unserialize() */
    public function unserialize($serialized)
    {
        list (
            $this->id,
            $this->email,
            $this->password,
            $this->active,
            // see section on salt below
            // $this->salt
        ) = unserialize($serialized);
    }

    /**
    * Get the value of Information
    *
    * @return mixed
    */
    public function getInformation()
    {
        return $this->information;
    }

    /**
    * Set the value of Information
    *
    * @param mixed information
    *
    * @return self
    */
    public function setInformation($information)
    {
        $this->information = $information;

        return $this;
    }


    /**
    * Get the value of Note
    *
    * @return mixed
    */
    public function getNote()
    {
        return $this->note;
    }

    /**
    * Set the value of Note
    *

templates/layout/app/index.html.twig
<!DOCTYPE html>
<html lang="{{ app.request.locale }}">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <link rel="profile" href="http://gmpg.org/xfn/11">
        <title>{% block title %}{% if meta_title is defined %}{{ meta_title }}{% else %}{{ page_title }}{% endif %} - {{settingservice.get('site.name')|striptags}}{% endblock %}</title>
{% set template = templateservice.getTemplate() %}
{% block tracking %}
        {% set trackingCode = settingservice.get('site.tracking') %}
        {{trackingCode|raw}}
{% endblock %}

{% block meta %}
        <meta name="HandheldFriendly" content="True">
        <meta name="MobileOptimized" content="320">
        {% if meta_keywords is defined %}<meta name="keywords" content="{{ meta_keywords }}">{% endif %}

        {% if meta_description is defined %}<meta name="description" content="{{ meta_description }}">{% endif %}

        <meta property="og:type" content="website">
        {% if meta_title is defined %}<meta property="og:title" content="{{ meta_title }}">{% endif %}

        {% if meta_description is defined %}<meta property="og:description" content="{{ meta_description }}">{% endif %}

        <meta property="og:url" content="{{settingservice.get('site.url')}}">
        <meta property="og:site_name" content="{{settingservice.get('site.name')|striptags}}">
        {% if page_image is defined %}
        <meta property="og:image" content="{{page_image.url}}">
        <meta property="og:image:width" content="{{page_image.width}}">
        <meta property="og:image:height" content="{{page_image.height}}">
        {% endif %}
        <meta property="og:locale" content="en_US">
        {% if meta_title is defined %}<meta name="twitter:text:title" content="{{ meta_title }}">{% endif %}

        <meta name="twitter:card" content="summary">
{% endblock %}
{% block stylesheets %}
        {{ encore_entry_link_tags('app') }}
        <link href="https://cdn.jsdelivr.net/npm/@mdi/font@5.x/css/materialdesignicons.min.css" rel="stylesheet">
        <link rel="stylesheet" type="text/css" href="{{ asset('/') }}css/app.css?v={{settingservice.get('template.assets.version')}}">
        <link rel="shortcut icon" href="{{ asset('favicon.png') }}" type="image/png">
{% endblock %}
        <script src="https://kit.fontawesome.com/f4e4c62af9.js"></script>
        {{blockservice.getBlock('head')|raw}}
    </head>
    <body data-locale="{{ app.request.locale }}">
        {% if disable_layout is not defined or (disable_layout is defined and disable_layout == false) %}
            {% if template.settings.header == 'standard' %}
                {% include 'layout/app/components/header.html.twig' %}
            {% elseif template.settings.header == 'top' %}
                {% include 'layout/app/components/header-top.html.twig' %}
            {% elseif template.settings.header == 'centered' %}
                {% include 'layout/app/components/header-centered.html.twig' %}
            {% elseif template.settings.header == 'overlay' %}
                {% include 'layout/app/components/header-overlay.html.twig' %}
            {% endif %}
        {% endif %}
        <main class="main-content">
            {% block content %}{% endblock %}
        </main>
        {% if disable_layout is not defined or (disable_layout is defined and disable_layout == false) %}
            {% if template.settings.footer == 'standard' %}
                {% include 'layout/app/components/footer.html.twig' %}
            {% elseif template.settings.footer == 'top' %}
                {% include 'layout/app/components/footer-bottom.html.twig' %}
            {% elseif template.settings.footer == 'centered' %}
                {% include 'layout/app/components/footer-centered.html.twig' %}
            {% endif %}
            <a id="site-scroll-to-top" class="pointer"><i class="fas fa-angle-up" aria-hidden="true"></i><span>Back to top</span></a>
        {% endif %}

        {% block javascripts %}
            {{ encore_entry_script_tags('app') }}
        {% endblock %}
        {% block bottom %}
            {% if settingservice.get('language.switch.enabled') %}
            <div id="language-switcher-bar">
                <div class="container text-center">
                    {% trans %}The content of this website is available in other languages.{% endtrans %}

                    {% set activeLocales = localeservice.getActiveLocales() %}
                    {% if activeLocales is not empty and activeLocales|length > 1 %}
                        {% for activeLocale in activeLocales %}
                            <a href="{% if activeLocale.default is not empty %}/{% else %}/{{activeLocale.locale}}/{% endif %}" class="btn btn-sm btn-secondary">
                                <img src="{{ asset('/') }}img/flags/{{activeLocale.lcid}}.png" alt="{{activeLocale.name}}">
                                {{activeLocale.name}}
                            </a>
                        {% endfor %}
                    {% endif %}
                </div>
                <a id="language-switcher-close"><i class="fal fa-times"></i></a>
            </div>
            <script>
                document.addEventListener('DOMContentLoaded', function(event) {
                    if (document.getElementById('language-switcher-close') != null) {
                        document.getElementById('language-switcher-close').addEventListener('click', function() {
                            document.getElementById('language-switcher-bar').style.top = "-80px";
                        });
                    }
                    if (document.getElementById('language-switcher-open') != null) {
                        document.getElementById('language-switcher-open').addEventListener('click', function() {
                            document.getElementById('language-switcher-bar').style.top = "0";
                        });
                    }
                });
            </script>
            {% endif %}
        {% endblock %}
    </body>
</html>

templates/layout/app/page.html.twig
{% extends 'layout/app/index.html.twig' %}

{% block content %}
    {{content|raw}}
{% endblock %}

{% block meta %}
    {{ parent() }}
{% endblock %}

{% block stylesheets %}
    {{ parent() }}
    <style>
    {% if custom_css %}
    {{custom_css|raw}}
    {% endif %}
    </style>
{% endblock %}

{% block javascripts %}
    {{ parent() }}
    {% if custom_js %}
    <script>
    {% if custom_js %}
    {{custom_js|raw}}
    {% endif %}
    </script>
    {% endif %}
{% endblock %}